export const dashboardCopy = {
  ka: {
    title: 'პირადი კაბინეტი',
    subtitle: 'სერვისები, შეკვეთები და თქვენი მონაცემები.',
    navigation: 'კაბინეტის განყოფილებები',
    overview: 'მიმოხილვა',
    services: 'ჩემი სერვისები',
    purchases: 'ჩემი შესყიდვები',
    comments: 'ჩემი კომენტარები',
    addresses: 'მისამართები',
    payments: 'გადახდები',
    password: 'პაროლი',
    profile: 'პროფილი',
    customer: 'მომხმარებელი',
    corporate: 'კორპორატიული ანგარიში',
    welcome: 'მოგესალმებით,',
    greeting: 'გამარჯობა,',
    editProfile: 'პროფილის რედაქტირება',
    currentServices: 'მიმდინარე სერვისები',
    completedServices: 'დასრულებული სერვისები',
    currentPurchases: 'მიმდინარე შეკვეთები',
    completedPurchases: 'დასრულებული შეკვეთები',
    noCurrentPurchases: 'მიმდინარე შეკვეთები არ გაქვთ',
    noCompletedPurchases: 'დასრულებული შეკვეთები ჯერ არ გაქვთ',
    noCompletedServices: 'დასრულებული სერვისები ჯერ არ გაქვთ',
    noCurrentPurchasesText: 'თქვენი ახალი შეკვეთები ამ განყოფილებაში გამოჩნდება.',
    noCompletedPurchasesText: 'დასრულებული შეკვეთების ისტორია აქ შეინახება.',
    noCompletedServicesText: 'მომსახურების დასრულებისა და მოწყობილობის გატანის შემდეგ ჩანაწერი აქ გამოჩნდება.',
    backToPurchases: 'უკან დაბრუნება',
    overviewHint: 'ნახეთ მიმდინარე მდგომარეობა და ბოლო ჩანაწერები.',
    servicesHint: 'მოწყობილობების მიმდინარე მდგომარეობა და მომსახურების ისტორია.',
    purchasesHint: 'შეკვეთები, პროდუქტები და გადახდის მდგომარეობა.',
    profileHint: 'თქვენს ანგარიშთან დაკავშირებული საკონტაქტო ინფორმაცია.',
    logout: 'გასვლა',
    loggingOut: 'გასვლა…',
    actionError: 'მოქმედება ვერ შესრულდა. სცადეთ ხელახლა.',
    previewTitle: 'საცდელი ვერსია',
    serviceCount: 'ჩემი სერვისები',
    inService: 'მიმდინარეობს',
    ready: 'მზად არის',
    purchaseCount: 'შესყიდვები',
    recentServices: 'მიმდინარე სერვისები',
    recentPurchases: 'ბოლო შესყიდვები',
    viewAll: 'ყველას ნახვა',
    all: 'ყველა',
    openServices: 'მიმდინარე',
    history: 'დასრულებული',
    noActiveServices: 'მიმდინარე სერვისები არ გაქვთ',
    noActiveServicesText: 'წინა მომსახურების სანახავად გახსენით „დასრულებული სერვისები“.',
    searchServices: 'მოძებნეთ კოდით ან მოწყობილობით',
    searchPurchases: 'მოძებნეთ შეკვეთით ან პროდუქტით',
    serviceSearchPlaceholder: 'კოდი ან მოწყობილობა',
    purchaseSearchPlaceholder: 'შეკვეთა ან პროდუქტი',
    clearSearch: 'ძიების გასუფთავება',
    status: 'სტატუსი',
    allStatuses: 'ყველა სტატუსი',
    results: 'ნაპოვნი ჩანაწერები',
    noServices: 'სერვისის ჩანაწერები ჯერ არ არის',
    noServicesText: 'ამ ანგარიშთან დაკავშირებული სერვისები აქ გამოჩნდება.',
    noPurchases: 'შესყიდვები ჯერ არ არის',
    noPurchasesText: 'თქვენი შეძენილი პროდუქტები და შეკვეთების დეტალები აქ გამოჩნდება.',
    noResults: 'ჩანაწერი ვერ მოიძებნა',
    noResultsText: 'შეცვალეთ საძიებო სიტყვა ან არჩეული ფილტრი.',
    resetFilters: 'ფილტრების გასუფთავება',
    service: 'სერვისი',
    serviceRecord: 'სერვისის ბარათი',
    order: 'შეკვეთა',
    noCode: 'კოდი ჯერ არ არის მინიჭებული',
    device: 'მოწყობილობა',
    model: 'მოდელი',
    serialNumber: 'სერიული ნომერი',
    registered: 'გაფორმების თარიღი',
    registeredTime: 'გაფორმების დრო',
    price: 'ფასი',
    serviceDetails: 'სერვისის დეტალები',
    localTime: 'დრო მითითებულია საქართველოს დროით',
    devices: 'მოწყობილობები',
    issue: 'მიმართვის მიზეზი',
    resolution: 'სამუშაოს შედეგი',
    created: 'მიღების თარიღი',
    purchased: 'შეკვეთის თარიღი',
    updated: 'ბოლო განახლება',
    estimate: 'სავარაუდო ღირებულება',
    details: 'დეტალების ნახვა',
    total: 'ჯამი',
    payment: 'გადახდა',
    product: 'პროდუქტი',
    quantity: 'რაოდენობა',
    unitPrice: 'ერთეულის ფასი',
    itemCount: 'პროდუქტის ჩანაწერი',
    missing: 'მითითებული არ არის',
    name: 'სახელი და გვარი',
    email: 'ელფოსტა',
    phone: 'ტელეფონი',
    accountType: 'ანგარიშის ტიპი',
    company: 'კომპანიის დასახელება',
    taxId: 'საიდენტიფიკაციო კოდი',
    contactData: 'საკონტაქტო მონაცემები',
    profileNote: 'მონაცემების შეცვლა გსურთ? დაგვიკავშირდით, რომ ინფორმაცია გადავამოწმოთ და განვაახლოთ.',
    changeContact: 'მონაცემების შეცვლის მოთხოვნა',
    needHelp: 'გაქვთ შეკითხვა?',
    helpText: 'დაგვიკავშირდით სერვისის ან შეკვეთის შესახებ.',
    contact: 'დაგვიკავშირდით',
    privacy: 'კონფიდენციალურობა',
    statusLabels: {
      new: 'მიღებულია', in_progress: 'მიმდინარეობს', waiting_for_part: 'ნაწილის მოლოდინში',
      ready: 'მზად არის', could_not_fix: 'შეკეთება ვერ მოხერხდა', picked_up: 'ჩაბარებულია',
      processing: 'მუშავდება', completed: 'დასრულებულია', cancelled: 'გაუქმებულია',
      shipped: 'გაგზავნილია', delivered: 'მიწოდებულია', returned: 'დაბრუნებულია', partial_return: 'ნაწილობრივ დაბრუნებულია',
      unpaid: 'გადაუხდელია', partial: 'ნაწილობრივ გადახდილია', paid: 'გადახდილია',
      refunded: 'თანხა დაბრუნებულია', partial_refund: 'ნაწილობრივ დაბრუნებულია',
      refund_pending: 'თანხის დაბრუნების მოლოდინში', void: 'გადახდა გაუქმებულია',
    } as Record<string, string>,
    deviceLabels: {
      laptop: 'ლეპტოპი', desktop: 'კომპიუტერი', drone: 'დრონი', data_recovery: 'ინფორმაციის აღდგენა',
      non_standard_board: 'არასტანდარტული პლატა', phone: 'ტელეფონი', tablet: 'პლანშეტი',
      console: 'კონსოლი', television: 'ტელევიზორი', other: 'სხვა მოწყობილობა',
    } as Record<string, string>,
  },
  en: {
    title: 'My account',
    subtitle: 'Services, orders and your personal details.',
    navigation: 'Account sections',
    overview: 'Overview',
    services: 'My services',
    purchases: 'My purchases',
    comments: 'My comments',
    addresses: 'Addresses',
    payments: 'Payments',
    password: 'Password',
    profile: 'Profile',
    customer: 'Customer',
    corporate: 'Business account',
    welcome: 'Welcome,',
    greeting: 'Hello,',
    editProfile: 'Edit profile',
    currentServices: 'Current services',
    completedServices: 'Completed services',
    currentPurchases: 'Current orders',
    completedPurchases: 'Completed orders',
    noCurrentPurchases: 'You have no current orders',
    noCompletedPurchases: 'No completed orders yet',
    noCompletedServices: 'No completed services yet',
    noCurrentPurchasesText: 'Your new orders will appear in this section.',
    noCompletedPurchasesText: 'Your completed order history will appear here.',
    noCompletedServicesText: 'Service records appear here after the device has been handed back to you.',
    backToPurchases: 'Go back',
    overviewHint: 'See the current status and your latest records.',
    servicesHint: 'Your devices’ current status and service history.',
    purchasesHint: 'Your orders, products and payment status.',
    profileHint: 'The contact information linked to your account.',
    logout: 'Sign out',
    loggingOut: 'Signing out…',
    actionError: 'The action could not be completed. Please try again.',
    previewTitle: 'Account preview',
    serviceCount: 'Service records',
    inService: 'In progress',
    ready: 'Ready',
    purchaseCount: 'Purchases',
    recentServices: 'Active services',
    recentPurchases: 'Latest purchases',
    viewAll: 'View all',
    all: 'All',
    openServices: 'Active',
    history: 'Completed',
    noActiveServices: 'No active services',
    noActiveServicesText: 'Open “Completed services” to see your previous services.',
    searchServices: 'Search by code or device',
    searchPurchases: 'Search by order or product',
    serviceSearchPlaceholder: 'Code or device',
    purchaseSearchPlaceholder: 'Order or product',
    clearSearch: 'Clear search',
    status: 'Status',
    allStatuses: 'All statuses',
    results: 'Matching records',
    noServices: 'No service records yet',
    noServicesText: 'Services linked to this account will appear here.',
    noPurchases: 'No purchases yet',
    noPurchasesText: 'Purchases linked to this account will appear here.',
    noResults: 'No matching records',
    noResultsText: 'Try a different search or change the selected filter.',
    resetFilters: 'Clear filters',
    service: 'Service',
    serviceRecord: 'Service record',
    order: 'Order',
    noCode: 'A code has not been assigned yet',
    device: 'Device',
    model: 'Model',
    serialNumber: 'Serial number',
    registered: 'Registered on',
    registeredTime: 'Registration time',
    price: 'Price',
    serviceDetails: 'Service details',
    localTime: 'All times shown in Georgia time',
    devices: 'Devices',
    issue: 'Reported issue',
    resolution: 'Work outcome',
    created: 'Received on',
    purchased: 'Order date',
    updated: 'Last updated',
    estimate: 'Estimated cost',
    details: 'View details',
    total: 'Total',
    payment: 'Payment',
    product: 'Product',
    quantity: 'Quantity',
    unitPrice: 'Unit price',
    itemCount: 'Product entries',
    missing: 'Not provided',
    name: 'Full name',
    email: 'Email',
    phone: 'Phone',
    accountType: 'Account type',
    company: 'Company name',
    taxId: 'Tax ID',
    contactData: 'Contact information',
    profileNote: 'Need to change your information? Contact us so we can verify and update it.',
    changeContact: 'Request a contact update',
    needHelp: 'Have a question?',
    helpText: 'Get in touch about your service or order.',
    contact: 'Contact us',
    privacy: 'Privacy',
    statusLabels: {
      new: 'Received', in_progress: 'In progress', waiting_for_part: 'Waiting for a part',
      ready: 'Ready', could_not_fix: 'Could not be repaired', picked_up: 'Picked up',
      processing: 'Processing', completed: 'Completed', cancelled: 'Cancelled',
      shipped: 'Shipped', delivered: 'Delivered', returned: 'Returned', partial_return: 'Partially returned',
      unpaid: 'Unpaid', partial: 'Partially paid', paid: 'Paid',
      refunded: 'Refunded', partial_refund: 'Partially refunded',
      refund_pending: 'Refund pending', void: 'Payment voided',
    } as Record<string, string>,
    deviceLabels: {
      laptop: 'Laptop', desktop: 'Computer', drone: 'Drone', data_recovery: 'Data recovery',
      non_standard_board: 'Non-standard circuit board', phone: 'Phone', tablet: 'Tablet',
      console: 'Game console', television: 'Television', other: 'Other device',
    } as Record<string, string>,
  },
}

export type DashboardCopy = (typeof dashboardCopy)['ka']
